name: "Docs: Check and Deploy"

on:
  push:
    branches: [main, github-actions-test]
  pull_request:
    branches: [main]
permissions:
  contents: write

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.11.3]
        torch-version: [2.0.1]
        include:
          - torch-version: 2.0.1

    steps:
      - uses: actions/checkout@v3
      - name: Build using Python ${{matrix.python-version}}
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}
          cache: "pip"
          cache-dependency-path: "pyproject.toml"
      - name: Install dependencies [pip]
        run: |
          pip install --upgrade pip setuptools wheel
          pip install -e .[doc]
          pip install torch==${{ matrix.torch-version}} --extra-index-url https://download.pytorch.org/whl/cpu
      - name: Install Pandoc [apt-get]
        run: |
          sudo apt-get -y install pandoc
      - name: Generate Docs [Sphinx]
        run: |
          sphinx-build  -b html -D version=latest -D release=latest docs docs/_build
      - name: Deploy Docs
        uses: JamesIves/github-pages-deploy-action@v4
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && github.repository == 'pyt-team/TopoModelX' }}
        with:
          branch: main
          folder: docs/_build
          token: ${{ secrets.DOCUMENTATION_KEY }}
          repository-name: pyt-team/pyt-team.github.io
          target-folder: topomodelx
          clean: true