name: "Docs: Check and Deploy"

on:
  push:
    branches: [main, github-actions-test]
  pull_request:
    branches: [main]
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        torch-version: [2.8.0]

    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Set up Python
        uses: astral-sh/setup-uv@v10.0.1
        with:
          enable-cache: true

      - name: Install PyTorch ${{ matrix.torch-version }}+cpu
        run: |
          uv venv
          uv pip install torch==${{ matrix.torch-version}} --extra-index-url https://download.pytorch.org/whl/cpu
          uv pip install pyg_lib -f https://data.pyg.org/whl/torch-${{ matrix.torch-version }}+cpu.html

      - name: Install main package
        run: uv pip install -e .[doc]

      - name: Install Pandoc [apt-get]
        run: |
          sudo apt-get -y install pandoc

      - name: Generate Docs [Sphinx]
        run: uv run sphinx-build  -b html -D version=latest -D release=latest docs docs/_build

      - name: Deploy Docs
        uses: JamesIves/github-pages-deploy-action@v4
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && github.repository == 'pyt-team/TopoModelX' }}
        with:
          branch: main
          folder: docs/_build
          token: ${{ secrets.DOCUMENTATION_KEY }}
          repository-name: pyt-team/pyt-team.github.io
          target-folder: topomodelx
          clean: true
