name: "Testing Codebase"

on:
  workflow_dispatch:
  push:
    branches: [main,github-actions-test]
    paths-ignore:
    - 'docs/**'
    - 'README.md'
    - 'LICENSE.txt'
    - '.gitignore'

  pull_request:
    branches: [main]
    paths-ignore:
    - 'docs/**'
    - 'README.md'
    - 'LICENSE.txt'
    - '.gitignore'

jobs:

  pytest:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]
        torch-version: ["2.3.0"]

    steps:
      - uses: actions/checkout@v5

      - name: Set up Python ${{ matrix.python-version }}
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true

      - name: Install PyTorch ${{ matrix.torch-version }}+cpu
        run: |
          uv pip install torch==${{ matrix.torch-version}} --extra-index-url https://download.pytorch.org/whl/cpu
          uv pip install torch-scatter -f https://data.pyg.org/whl/torch-${{ matrix.torch-version }}+cpu.html
          uv pip install torch-sparse -f https://data.pyg.org/whl/torch-${{ matrix.torch-version }}+cpu.html
          uv pip install torch-cluster -f https://data.pyg.org/whl/torch-${{ matrix.torch-version }}+cpu.html

      - name: Install main package
        run: uv pip install -e .[all]

      - name: Typecheck [mypy]
        run: uv run mypy -p topomodelx

      - name: Run tests for codebase [pytest]
        run: uv run pytest --cov --cov-report=xml:coverage.xml test/nn test/base test/utils

      - name: Upload coverage
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          fail_ci_if_error: false
